name: Bump PyPI requirements
on:
  schedule:
    - cron: '53 8 * * *'
jobs:
  do-the-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip pip-tools
          for reqsin in requirements.in dev-requirements.in; do
            pip-compile -U --no-header "$reqsin"
          done

      - name: push it
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am 'Bump PyPI requirements [Automated]' && git push || true
